.\" Manpage for adb.
.TH ADB 1

.SH NAME
adb \- Android Debug Bridge

.SH SYNOPSIS
adb [GLOBAL_OPTIONS] command [COMMAND_OPTIONS]

.SH DESCRIPTION
adb is a client to adb server (which must be running on the same machine).

.SH GLOBAL_OPTIONS
.IP -a
Listen on all network interfaces, not just localhost
.IP -d
Use USB device (error if multiple devices connected)
.IP -e
Use TCP/IP device (error if multiple TCP/IP devices available)
.IP -s \fISERIAL\fR
Use device with given serial (overrides $ANDROID_SERIAL)
.IP -t \fIID\fR
Use device with given transport id
.IP -H
Name of adb server host [default=localhost]
.IP -P
Port of adb server [default=5037]
.IP -L \fISOCKET\fR
Listen on given socket for adb server [default=tcp:localhost:5037]

.SH COMMANDS

.SH exec-out [\fISHELL_COMMAND\fR]
Variant of shell. Run Forwards raw device stdout to host stdout.

.SH exec-in [SHELL COMMAND]
Variant of shell. Forwards raw device stdout to host stdout.

.SH EXAMPLES
Here comes examples on how to start adb server in debug mode etc.

.SH BUGS
No known bugs.
